name: Embedding Store CI
on: [push]
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                - os: macos-latest
                  config: mac
                - os: ubuntu-latest
                  config: linux
        steps:
        - uses: actions/checkout@v1

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: "2.7"

        - name: Install deps
          run: |
              bash install_deps.sh
        - name: Mount bazel cache
          uses: actions/cache@v1
          with:
              path: "/home/runner/.cache/bazel"
              key: ${{ runner.os }}-bazel

        - name: Lint
          run: ./lint.sh

        - name: Build
          run: bazel build --config=${{ matrix.config }} //...

        - name: Test
          run: bazel test --config=${{ matrix.config }} --test_output=all //...
